# See http://about.travis-ci.org/docs/user/build-configuration/

language: scala

scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.11.11
      jdk: openjdk7
    - scala: 2.11.11
      jdk: oraclejdk7

script:
  - sbt clean compile coverage test && sbt coverageAggregate

before_install:
  - pip install --user codecov

after_success:
  - codecov